services:
  dofuseye-server:
    container_name: dofuseye-server
    build: .
    expose:
      - "8000"
    env_file:
      - .env
    command: gunicorn -b 0.0.0:8000 wgsi:app
  nginx:
    container_name: nginx
    build: ./services/nginx
    ports:
      - "80:80"
    depends_on:
      - dofuseye-server