version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/nginx:/etc/nginx/conf.d
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  # dofuseye-server:
  #   container_name: dofuseye-server
  #   build: .
  #   expose:
  #     - "8000"
  #   env_file:
  #     - .env
  #   command: gunicorn -b 0.0.0:8000 wgsi:app
  # nginx:
  #   container_name: nginx
  #   build: ./services/nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - dofuseye-server
