"""empty message

Revision ID: 64338bec9a27
Revises: 
Create Date: 2021-12-30 15:43:56.505397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64338bec9a27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('character_name', sa.Text(), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('character_name'),
    sa.UniqueConstraint('character_name')
    )
    op.create_table('perc_prism',
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('modified', sa.Integer(), nullable=True),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('sword', sa.Text(), nullable=False),
    sa.Column('w1_name', sa.Text(), nullable=True),
    sa.Column('w1_class', sa.Text(), nullable=True),
    sa.Column('w1_dead', sa.Integer(), nullable=True),
    sa.Column('w2_name', sa.Text(), nullable=True),
    sa.Column('w2_class', sa.Text(), nullable=True),
    sa.Column('w2_dead', sa.Integer(), nullable=True),
    sa.Column('w3_name', sa.Text(), nullable=True),
    sa.Column('w3_class', sa.Text(), nullable=True),
    sa.Column('w3_dead', sa.Integer(), nullable=True),
    sa.Column('w4_name', sa.Text(), nullable=True),
    sa.Column('w4_class', sa.Text(), nullable=True),
    sa.Column('w4_dead', sa.Integer(), nullable=True),
    sa.Column('w5_name', sa.Text(), nullable=True),
    sa.Column('w5_class', sa.Text(), nullable=True),
    sa.Column('w5_dead', sa.Integer(), nullable=True),
    sa.Column('l1_name', sa.Text(), nullable=True),
    sa.Column('l1_class', sa.Text(), nullable=True),
    sa.Column('l1_dead', sa.Integer(), nullable=True),
    sa.Column('l2_name', sa.Text(), nullable=True),
    sa.Column('l2_class', sa.Text(), nullable=True),
    sa.Column('l2_dead', sa.Integer(), nullable=True),
    sa.Column('l3_name', sa.Text(), nullable=True),
    sa.Column('l3_class', sa.Text(), nullable=True),
    sa.Column('l3_dead', sa.Integer(), nullable=True),
    sa.Column('l4_name', sa.Text(), nullable=True),
    sa.Column('l4_class', sa.Text(), nullable=True),
    sa.Column('l4_dead', sa.Integer(), nullable=True),
    sa.Column('l5_name', sa.Text(), nullable=True),
    sa.Column('l5_class', sa.Text(), nullable=True),
    sa.Column('l5_dead', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fight_id'),
    sa.UniqueConstraint('fight_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perc_prism')
    op.drop_table('aliases')
    # ### end Alembic commands ###
